In [14]:
import pandas as pd

In [15]:
all_data = pd.read_csv('all_data.csv')

In [16]:
all_data.head()

,date,open_AAPL,high_AAPL,low_AAPL,close_AAPL,volume_AAPL,log_returns_AAPL,open_AMZN,high_AMZN,low_AMZN,...,low_SPY,close_SPY,volume_SPY,log_returns_SPY,open_GM,high_GM,low_GM,close_GM,volume_GM,log_returns_GM
0,2021-06-30 13:00:00,136120000000,137020000000,135800000000,136190000000,2319337,0.840930,3444550000000,3471180000000,3434500000000,...,426980000000,427540000000,899314,1.977464,58780000000,59230000000,58610000000,59180000000,94860,-2.603428
1,2021-06-30 14:00:00,136190000000,137130000000,136170000000,136990000000,1233138,0.838986,3463280000000,3471300000000,3456950000000,...,427520000000,428210000000,913148,0.457163,59200000000,59460000000,59120000000,59200000000,206119,-3.716731
2,2021-06-30 15:00:00,137000000000,137190000000,136640000000,136690000000,817256,-1.763051,3467490000000,3471780000000,3455720000000,...,427800000000,427970000000,728649,1.981685,59210000000,59210000000,58925000000,58990000000,170695,-0.842540
3,2021-06-30 16:00:00,136700000000,136930000000,136475000000,136710000000,708786,0.838039,3467450000000,3467980000000,3451380000000,...,427730000000,428010000000,957142,0.459762,58990000000,59230000000,58925000000,59135000000,130218,-1.979324
4,2021-06-30 17:00:00,136700000000,137040000000,136680000000,136980000000,603442,2.203817,3456030000000,3463490000000,3455520000000,...,427790000000,427890000000,463073,1.979804,59135000000,59150000000,59010000000,59090000000,74917,-0.840773

In [17]:
close_columns = ['date']+[col for col in all_data.columns if 'close' in col] 
close_columns

['date',
 'close_AAPL',
 'close_AMZN',
 'close_MSFT',
 'close_META',
 'close_GOOGL',
 'close_NVDA',
 'close_SPY',
 'close_GM']

In [18]:
close_data = all_data[close_columns]

#rename date to ts_event
close_data = close_data.rename(columns={'date':'ts_event'})

In [21]:
close_data.head()

close_data['month'] = close_data.ts_event.dt.month

AttributeError: Can only use .dt accessor with datetimelike values

In [20]:
close_data.to_csv('./dataset/close_data.csv', index=False)